In [1]:
import os 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import cv2

In [2]:
data_ML = pd.read_csv('TrainingSet_MLFeatures.csv')
data_DL = pd.read_csv('TrainingSet_DLFeatures.csv')

In [3]:
data_ML

0             1             2             3  \
0         COVID-978.png_1.png  [0.40915435]  [0.99619466]  [2.70940102]   
1        COVID-1168.png_2.png   [0.4191659]  [0.99372753]  [2.84194827]   
2        Normal-797.png_1.png  [0.56481894]   [0.9958111]  [2.07246957]   
3       Normal-2286.png_1.png  [0.46483319]  [0.99541339]  [2.56189942]   
4        COVID-1221.png_2.png  [0.37212985]  [0.99413938]  [2.87610106]   
...                       ...           ...           ...           ...   
11243   Normal-9147.png_1.png  [0.31801952]  [0.99338882]  [2.46734865]   
11244   Normal-2349.png_1.png  [0.45670776]  [0.99541801]  [2.19929132]   
11245    Normal-754.png_1.png  [0.48046798]   [0.9959611]  [2.46620756]   
11246    COVID-1437.png_2.png  [0.24867096]  [0.99581114]   [3.2570868]   
11247  Normal-10154.png_2.png  [0.34620935]  [0.99307602]  [2.63543001]   

                  4              5             6             7             8  \
0      [0.62954441]  [61.52722614]  [0.16740728]  [0.99619466]  [0.40496537]   
1      [0.60535143]  [66.34467088]  [0.17570006]  [0.99372753]  [0.41355551]   
2      [0.71954693]  [40.57367072]  [0.31902043]   [0.9958111]  [0.56327168]   
3      [0.65807098]  [62.14001441]   [0.2160699]  [0.99541339]  [0.46226531]   
4      [0.58472712]  [69.34863469]  [0.13848063]  [0.99413938]  [0.36585222]   
...             ...            ...           ...           ...           ...   
11243  [0.59692866]  [40.79029869]  [0.10113641]  [0.99338882]  [0.31135507]   
11244  [0.67654215]  [43.14207639]  [0.20858198]  [0.99541801]  [0.45412488]   
11245  [0.65895675]  [49.92813101]  [0.23084948]   [0.9959611]  [0.47822905]   
11246  [0.53662367]  [66.66832159]  [0.06183725]  [0.99581114]  [0.24499921]   
11247    [0.601922]  [53.61080637]  [0.11986091]  [0.99307602]  [0.34013519]   

                  9  ...   274   275   276   277    278   279   280   281  \
0      [0.99417082]  ...   0.0  81.0  97.0   0.0  105.0  59.0   0.0   5.0   
1      [0.98271618]  ...  14.0   9.0   8.0   9.0    0.0   3.0   4.0   3.0   
2      [0.99440849]  ...   9.0   6.0   0.0   6.0    3.0   3.0   0.0   5.0   
3      [0.99287162]  ...  32.0   0.0  31.0  52.0    0.0  39.0  13.0   0.0   
4      [0.98159372]  ...  26.0  15.0  18.0  20.0    0.0  11.0   6.0   2.0   
...             ...  ...   ...   ...   ...   ...    ...   ...   ...   ...   
11243  [0.98112644]  ...   9.0  10.0   0.0   7.0    5.0   2.0   0.0   1.0   
11244  [0.99369061]  ...   0.0  12.0   1.0   0.0    1.0   0.0   0.0   1.0   
11245  [0.99485932]  ...  26.0   0.0  22.0  16.0   18.0   0.0  12.0  19.0   
11246  [0.99377049]  ...   0.0  78.0  71.0   0.0   55.0  26.0   0.0  23.0   
11247  [0.98171483]  ...  15.0   9.0   0.0  15.0    9.0   7.0   0.0   4.0   

        282   283  
0       1.0   1.0  
1       2.0   1.0  
2       1.0   1.0  
3       5.0   3.0  
4       0.0   2.0  
...     ...   ...  
11243   2.0   1.0  
11244   0.0   2.0  
11245  10.0  10.0  
11246   3.0   3.0  
11247   2.0   2.0  

[11248 rows x 284 columns]

In [4]:
data_DL

0    1         2    3    4         5         6  \
0       COVID-3063.png_1.png  0.0  6.214828  0.0  0.0  0.000000  0.000000   
1      Normal-3540.png_2.png  0.0  0.000000  0.0  0.0  0.000000  0.000000   
2       COVID-3067.png_2.png  0.0  2.135872  0.0  0.0  0.000000  0.000000   
3      Normal-3103.png_1.png  0.0  0.000000  0.0  0.0  0.000000  0.000000   
4      Normal-9419.png_2.png  0.0  0.000000  0.0  0.0  0.000000  0.000000   
...                      ...  ...       ...  ...  ...       ...       ...   
11243    COVID-198.png_2.png  0.0  0.000000  0.0  0.0  0.000000  0.000000   
11244     COVID-28.png_1.png  0.0  0.000000  0.0  0.0  0.288199  0.000000   
11245    Normal-29.png_1.png  0.0  0.000000  0.0  0.0  0.000000  0.000000   
11246   COVID-1134.png_1.png  0.0  0.000000  0.0  0.0  0.000000  0.699178   
11247   COVID-1761.png_2.png  0.0  0.425595  0.0  0.0  0.000000  0.000000   

              7         8         9  ...      8183      8184      8185  \
0      0.000000  0.000000  0.000000  ...  0.000000  0.000000  2.411019   
1      0.000000  0.000000  8.477232  ...  1.140412  0.000000  0.425876   
2      3.322752  6.365335  0.000000  ...  0.053598  0.365886  3.275329   
3      0.000000  9.599844  3.254015  ...  3.418770  1.582177  0.530931   
4      3.839680  0.000000  0.000000  ...  0.000000  0.000000  2.903766   
...         ...       ...       ...  ...       ...       ...       ...   
11243  2.789412  0.073770  3.007945  ...  0.000000  0.000000  0.000000   
11244  2.265378  0.000000  0.000000  ...  1.450559  0.000000  1.433817   
11245  3.651956  0.000000  3.445255  ...  0.653872  0.616795  1.451651   
11246  3.649038  2.035660  4.055863  ...  2.906353  2.070960  0.099405   
11247  5.123220  0.000000  0.654043  ...  1.187165  0.370983  1.500756   

           8186      8187  8188      8189      8190      8191      8192  
0      0.622688  1.549552   0.0  0.000000  1.718059  0.000000  0.000000  
1      0.000000  0.806615   0.0  0.000000  3.214019  0.107443  0.000000  
2      1.472804  0.759195   0.0  0.000000  1.318807  0.317367  0.204579  
3      0.980820  0.861289   0.0  0.000000  3.333457  2.428553  0.000000  
4      0.333533  0.000000   0.0  0.150571  2.607418  2.668057  1.890033  
...         ...       ...   ...       ...       ...       ...       ...  
11243  0.000000  0.000000   0.0  0.000000  3.817831  2.781264  0.000000  
11244  0.032640  1.735934   0.0  0.000000  2.863344  1.559994  0.012528  
11245  0.120357  0.787476   0.0  0.000000  3.892768  0.752744  0.000000  
11246  0.000000  0.191638   0.0  0.000000  2.934579  1.677576  0.000000  
11247  0.000000  0.393054   0.0  0.000000  4.060289  2.486420  0.243168  

[11248 rows x 8193 columns]

In [5]:
to_change = [i for i in data_ML.columns if data_ML[i].dtype != np.float64]
to_change.remove('0')

In [6]:
for i in to_change:
    data_ML[i] = data_ML[i].map(lambda x: str(x)[1:-1]).astype(np.float64)

In [7]:
merged = pd.merge(data_ML, data_DL, how='inner', on='0')

def convert_to_class(val):
    if val[:5] == "COVID":
        return 1
    else: return 0

merged['class'] = merged['0'].map(convert_to_class)

In [8]:
merged

0       1_x       2_x       3_x       4_x  \
0         COVID-978.png_1.png  0.409154  0.996195  2.709401  0.629544   
1        COVID-1168.png_2.png  0.419166  0.993728  2.841948  0.605351   
2       Normal-2286.png_1.png  0.464833  0.995413  2.561899  0.658071   
3        COVID-1221.png_2.png  0.372130  0.994139  2.876101  0.584727   
4        COVID-3499.png_1.png  0.513100  0.995890  2.625060  0.673777   
...                       ...       ...       ...       ...       ...   
11243   Normal-2349.png_1.png  0.456708  0.995418  2.199291  0.676542   
11244    Normal-754.png_1.png  0.480468  0.995961  2.466208  0.658957   
11245    Normal-754.png_1.png  0.480468  0.995961  2.466208  0.658957   
11246    COVID-1437.png_2.png  0.248671  0.995811  3.257087  0.536624   
11247  Normal-10154.png_2.png  0.346209  0.993076  2.635430  0.601922   

             5_x       6_x       7_x       8_x       9_x  ...      8184  \
0      61.527226  0.167407  0.996195  0.404965  0.994171  ...  1.209300   
1      66.344671  0.175700  0.993728  0.413556  0.982716  ...  0.413869   
2      62.140014  0.216070  0.995413  0.462265  0.992872  ...  2.174718   
3      69.348635  0.138481  0.994139  0.365852  0.981594  ...  0.247064   
4      58.035014  0.263271  0.995890  0.511173  0.995843  ...  0.223107   
...          ...       ...       ...       ...       ...  ...       ...   
11243  43.142076  0.208582  0.995418  0.454125  0.993691  ...  1.058224   
11244  49.928131  0.230849  0.995961  0.478229  0.994859  ...  0.259868   
11245  49.928131  0.230849  0.995961  0.478229  0.994859  ...  0.259868   
11246  66.668322  0.061837  0.995811  0.244999  0.993770  ...  0.000000   
11247  53.610806  0.119861  0.993076  0.340135  0.981715  ...  0.000000   

           8185      8186      8187      8188  8189      8190      8191  \
0      1.425369  0.000000  0.000000  0.000000   0.0  2.827138  2.434880   
1      0.000000  0.337576  0.558591  0.000000   0.0  2.956906  1.624416   
2      0.458893  0.000000  0.349636  0.106661   0.0  3.053887  1.622358   
3      1.508575  0.000000  0.084696  0.000000   0.0  2.436066  1.526908   
4      2.579721  0.850910  0.000000  0.000000   0.0  3.104751  0.000000   
...         ...       ...       ...       ...   ...       ...       ...   
11243  0.000000  0.178284  0.976672  0.000000   0.0  3.087711  2.660019   
11244  1.585537  0.846950  0.520662  0.000000   0.0  3.948329  1.440756   
11245  1.585537  0.846950  0.520662  0.000000   0.0  3.948329  1.440756   
11246  0.242820  0.434088  0.000000  0.000000   0.0  2.131150  2.819653   
11247  1.351256  0.527217  0.171873  0.000000   0.0  2.960375  0.920844   

           8192  class  
0      0.000000      1  
1      0.000000      1  
2      0.000000      0  
3      0.435868      1  
4      0.000000      1  
...         ...    ...  
11243  1.032012      0  
11244  0.218825      0  
11245  0.218825      0  
11246  0.000000      1  
11247  0.000000      0  

[11248 rows x 8477 columns]

In [9]:
def mean_absolute_deviation(col):
    mean = col.mean()
    total = 0
    for i in col:
        total += abs(i - mean)
    return total/len(col)

lst = list(merged.columns)
lst.remove('0')
lst.remove('class')

In [10]:
all_devs = []
for i in lst:
    all_devs.append((i, mean_absolute_deviation(merged[i])))
to_keep = [i for i in all_devs if i[1] > 0.75]
to_keep = [i[0] for i in to_keep]

In [11]:
filtered_merged = merged[['0'] + to_keep + ['class']]

In [12]:
filtered_merged.to_csv('AfterMADFiltering.csv', index=False)

In [12]:
df_features = merged[to_keep]
df_targets = merged['class']

In [13]:
df_features

5_x      10_x        12_x       19_x        26_x     29_x   30_x  \
0      61.527226  3.516479   94.295582  95.833180  208.545657  20847.0  863.0   
1      66.344671  5.223652  182.921937  65.160514   73.146353  21330.0  426.0   
2      62.140014  3.761628   96.638300  90.603900  196.773271  23579.0  335.0   
3      69.348635  6.281365  217.635866  93.132227   95.991615  18964.0  412.0   
4      58.035014  2.899375   58.807436  65.930273  181.236703  26004.0  616.0   
...          ...       ...         ...        ...         ...      ...    ...   
11243  43.142076  3.140783   59.473104  55.510070  131.703473  23140.0  347.0   
11244  49.928131  3.334433   63.615275  66.714446  163.298076  24377.0  335.0   
11245  49.928131  3.334433   63.615275  66.714446  163.298076  24377.0  335.0   
11246  66.668322  4.265881   98.858131  74.579036  177.799674  12726.0  818.0   
11247  53.610806  4.711878  141.464317  48.422005   57.346880  17657.0  395.0   

        31_x   32_x   33_x  ...      8120      8121      8126      8134  \
0      473.0    0.0  330.0  ...  2.727223  1.202894  6.080217  2.305877   
1      211.0  161.0  102.0  ...  2.104570  1.279695  7.042996  2.913529   
2        0.0  176.0  128.0  ...  2.280103  2.005480  6.276818  2.845385   
3      239.0  143.0  104.0  ...  2.706998  0.470402  6.254804  1.757580   
4      305.0    0.0  222.0  ...  0.682746  1.614887  5.695261  2.330999   
...      ...    ...    ...  ...       ...       ...       ...       ...   
11243  175.0    0.0  106.0  ...  1.653540  2.166226  7.720344  2.610506   
11244  159.0  118.0    0.0  ...  2.269362  1.996750  6.684005  2.426299   
11245  159.0  118.0    0.0  ...  2.269362  1.996750  6.684005  2.426299   
11246    0.0  423.0  281.0  ...  3.452185  2.218957  7.367283  3.486177   
11247  215.0    0.0  130.0  ...  0.000000  3.635896  7.116386  3.110582   

           8141      8150      8151      8160      8163      8176  
0      1.424340  3.129421  1.847309  3.870966  1.584728  1.088522  
1      1.881258  2.852533  2.868698  3.219014  2.724083  1.166504  
2      2.703408  1.078053  1.683435  4.073582  1.825505  0.919416  
3      3.179417  2.642020  3.675868  4.157207  2.886778  0.000000  
4      0.000000  3.000998  1.383737  2.834082  2.454439  3.071672  
...         ...       ...       ...       ...       ...       ...  
11243  2.543639  1.557637  2.042252  4.342309  0.767051  1.175362  
11244  0.369615  1.236316  2.010289  5.357902  2.150362  0.000000  
11245  0.369615  1.236316  2.010289  5.357902  2.150362  0.000000  
11246  0.985428  2.670679  2.349117  2.538406  2.619902  0.884997  
11247  2.790768  2.936240  1.136064  3.636782  1.112316  2.323514  

[11248 rows x 2527 columns]

In [14]:
df_targets

0        1
1        1
2        0
3        1
4        1
        ..
11243    0
11244    0
11245    0
11246    1
11247    0
Name: class, Length: 11248, dtype: int64

In [15]:
from sklearn import preprocessing
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [16]:
scaler = preprocessing.StandardScaler().fit(df_features)
df_features_scaled = scaler.transform(df_features)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(df_features_scaled, np.ravel(df_targets),
                                                            test_size = 0.30, random_state = 344)

# RBF Kernel

In [21]:
param_grid = {'C': [0.1, 1, 10, 100], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']}
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.502 total time= 1.4min
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.502 total time= 1.2min
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.502 total time= 1.1min
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.501 total time= 1.2min
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.502 total time= 1.2min
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.502 total time= 1.2min
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.502 total time= 1.3min
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.502 total time= 1.1min
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.501 total time= 1.1min
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.502 total time= 1.2min
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.502 total time= 1.3min
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [22]:
print(grid.best_params_)
print(grid.best_estimator_)

{'C': 100, 'gamma': 0.0001, 'kernel': 'rbf'}
SVC(C=100, gamma=0.0001)


In [23]:
grid_predictions = grid.predict(X_test)
print(classification_report(y_test, grid_predictions))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      1682
           1       0.92      0.92      0.92      1693

    accuracy                           0.92      3375
   macro avg       0.92      0.92      0.92      3375
weighted avg       0.92      0.92      0.92      3375



In [24]:
print(confusion_matrix(y_test, grid_predictions))

[[1549  133]
 [ 128 1565]]


# Linear Kernel

In [25]:
param_grid2 = {'C': [0.1, 1, 10, 100], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['linear']}
grid2 = GridSearchCV(SVC(), param_grid2, refit = True, verbose = 3)
grid2.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.884 total time=  26.8s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.858 total time=  27.9s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.872 total time=  26.1s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.881 total time=  26.6s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.875 total time=  29.6s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.884 total time=  24.5s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.858 total time=  25.1s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.872 total time=  24.2s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.881 total time=  24.3s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.875 total time=  26.5s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.884 total time=  26.9s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [26]:
print(grid2.best_params_)
print(grid2.best_estimator_)

{'C': 1, 'gamma': 1, 'kernel': 'linear'}
SVC(C=1, gamma=1, kernel='linear')


In [27]:
grid_predictions2 = grid2.predict(X_test)
print(classification_report(y_test, grid_predictions2))

              precision    recall  f1-score   support

           0       0.89      0.88      0.88      1682
           1       0.88      0.89      0.88      1693

    accuracy                           0.88      3375
   macro avg       0.88      0.88      0.88      3375
weighted avg       0.88      0.88      0.88      3375



In [28]:
print(confusion_matrix(y_test, grid_predictions2))

[[1479  203]
 [ 189 1504]]


# Polynomial Kernel

In [29]:
param_grid3 = {'C': [0.1, 1, 10, 100], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['poly']}
grid3 = GridSearchCV(SVC(), param_grid3, refit = True, verbose = 3)
grid3.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.917 total time=  53.4s
[CV 2/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.910 total time=  53.8s
[CV 3/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.924 total time=  53.7s
[CV 4/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.923 total time=  53.3s
[CV 5/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.920 total time=  53.2s
[CV 1/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.917 total time=  52.8s
[CV 2/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.910 total time=  49.3s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.924 total time=  52.7s
[CV 4/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.923 total time=  52.6s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.920 total time= 1.1min
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.917 total time=  53.1s
[CV 2/5] END ....C=0.1, gamma=0.01, kernel=poly

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['poly']},
             verbose=3)

In [30]:
print(grid3.best_params_)
print(grid3.best_estimator_)

{'C': 0.1, 'gamma': 0.01, 'kernel': 'poly'}
SVC(C=0.1, gamma=0.01, kernel='poly')


In [31]:
grid_predictions3 = grid3.predict(X_test)
print(classification_report(y_test, grid_predictions3))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93      1682
           1       0.93      0.93      0.93      1693

    accuracy                           0.93      3375
   macro avg       0.93      0.93      0.93      3375
weighted avg       0.93      0.93      0.93      3375



In [32]:
print(confusion_matrix(y_test, grid_predictions3))

[[1556  126]
 [ 119 1574]]


# Testing different SVCs with cross fold

In [24]:
model = SVC(C=100, gamma=0.0001)
scores = cross_val_score(model, X_train, y_train, cv=25)
np.mean(scores)

0.9264588009301384

In [26]:
model_lin = SVC(C=1, gamma=1, kernel='linear')
scores_lin = cross_val_score(model_lin, X_train, y_train, cv=25)
np.mean(scores_lin)

0.8902598321706603

In [27]:
model_poly = SVC(C=0.1, gamma=0.01, kernel='poly')
scores_poly = cross_val_score(model_poly, X_train, y_train, cv=25)
np.mean(scores_poly)

0.9335699120412495

# Linear model training and testing

In [28]:
model_linear = SVC(C=1, gamma=1, kernel='linear')
model_linear.fit(X_train, y_train)

SVC(C=1, gamma=1, kernel='linear')

In [30]:
predictions = model_linear.predict(df_features_scaled)

In [32]:
confusion_matrix(np.ravel(df_targets), predictions)

array([[5403,  203],
       [ 189, 5453]])

In [33]:
y = model_linear.decision_function(df_features_scaled)
w_norm = np.linalg.norm(model_linear.coef_)
distance_from_hyperplane = y / w_norm

In [35]:
sigmoid_distance = 1/(1 + np.exp(-distance_from_hyperplane))

In [43]:
sigmoid_distance

array([0.74392107, 0.53518509, 0.5477191 , ..., 0.19642299, 0.63959875,
       0.45132593])

In [45]:
distance_data = pd.DataFrame()
distance_data['image'] = merged['0']
distance_data['dist'] = sigmoid_distance

In [47]:
distance_data.to_csv('scan_distfromhyperplace.csv', index=False)